#!/bin/bash

# Usage: ./inspect jobdir
# See `inspect.jl` for details on arguments.

PROJDIR="$HOME/HPCJobs/AdaptiveComplexPulse"       # PRE-COMPILED JULIA PROJECT DIRECTORY
JULIASCRIPT="${PROJDIR}/inspect.jl"

julia --project="${PROJDIR}" "${JULIASCRIPT}" "$@"