#!/bin/bash

# Usage: ./init job matrix T
MODULE="AdaptiveWindows"

SCRIPT="
    using $MODULE;

    job = ARGS[1];
    matrix = ARGS[2];
    T = parse($MODULE.Float, ARGS[3]);

    _!.setup = $MODULE.SetupVariables(T=T);
    _!.outdir = \"\$(job)_\$(matrix)_\$(T)\";

    save();
    println(_!.outdir);
"

JOBDIR=$(julia --project=. -e "$SCRIPT" "$@")
cp "$1.jl" "$JOBDIR/script.jl"

echo $JOBDIR