#!/bin/bash

# Usage: ./inspect jobdir1 jobdir2 ...
MODULE="JuliaCon2023"

SCRIPT="
    using $MODULE;
    for dir in ARGS;
        load(dir);
        println(\"Job: \$dir\");
        inspect();
    end;
"

julia --project=. -e "$SCRIPT" "$@"