#!/bin/bash

# Usage: ./inspect matrix T r m
# See `init.jl` for details on arguments.

PROJDIR="$HOME/HPCJobs/ComplexTrotterizedPulse"       # PRE-COMPILED JULIA PROJECT DIRECTORY
JULIASCRIPT="${PROJDIR}/init.jl"

julia --project="${PROJDIR}" "${JULIASCRIPT}" "$@"