#!/bin/bash

# Usage: ./run matrix T r m
# See `init.jl` for details on arguments.

PROJDIR="$HOME/HPCJobs/ComplexTrotterizedPulse"       # PRE-COMPILED JULIA PROJECT DIRECTORY
JULIASCRIPT="${PROJDIR}/init.jl"
STARTSCRIPT="${PROJDIR}/start"

JOBDIR=$(julia --project="${PROJDIR}" "${JULIASCRIPT}" "$@")
                                        # CREATES STANDARDIZED DIRECTORY FOR GIVEN ARGS
$STARTSCRIPT $JOBDIR --from-init        # DISPATCHES OPTIMIZATION JOB TO SLURM